### ISSUE TITLE
[PD] Learn how to use Google Doc and Slides

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-HTML-CSS#27]
### Coursework content

1. Go to g.co/AppliedDigitalSkills
2. Click "Sign in" in the top right
3. Sign in with your Google account, or create a new one
4. Click "I am a student"
5. Click "Join a class" and enter class code: qchyyg
6. Start the Communicate Effectively at Work course
8. Do lessons "4 - Communicate Ideas in a Proposal" and "5. Present Information About Your Job"

### Estimated time in hours

1

### What is the purpose of this assignment?

The goal is for you to be comfortable using Google Docs and Google Slides, which you will use a lot in your professional life.

### How to submit

Share the results to the exercises of both lessons on your coursework board.

**Comment by kfklein15** [comment]
I don't think this website achieves the goal, so we'll have to re-think this

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/83)
