### ISSUE TITLE
[PD] Improve Your Programming Problem Solving

### ISSUE THREAD

**Issue by esma-g** [CodeYourFuture/Module-HTML-CSS#28]
### Coursework content

Read the article [6 Ways to Improve your Programming Problem Solving](https://www.7pace.com/blog/improve-your-programming-problem-solving?authuser=0). Write a reflection on what you learned from this article.

- Which of these tips do you already do?
- Which ones will you start doing?
- What action will you take to start? 

### Estimated time in hours

1

### What is the purpose of this assignment?

This exercise aims to help to improve your problem solving skills while programming.

### How to submit

Share your reflection on the ticket on your coursework board.

**Comment by kfklein15** [comment]
Will be moved to React

**Comment by maz786** [comment]
Kamino cloned this issue to [maz786/Coursework-Planner](https://github.com/maz786/Coursework-Planner/issues/82)
